# Generated by Django 6.0.1 on 2026-02-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='code',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note',
        ),
        migrations.AddField(
            model_name='cours',
            name='coefficient',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='note',
            name='valeur',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
